# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcNuOI7YkzvCu8JWR4acubOwPXzoYiab
"""

import os

__version__ = "0.1.0dev"
__docs__ = "Tooling for Kaggle BirdCLEF"
__author__ = "Jiri Borovec"
__author_email__ = "jirka@pytorchlightning.ai"

_PATH_PACKAGE = os.path.realpath(os.path.dirname(__file__))
_PATH_PROJECT = os.path.dirname(_PATH_PACKAGE)